create table task (id bigint generated by default as identity, name_task varchar(255), task varchar(255), primary key (id));


INSERT INTO task(name_task,task) VALUES('Task_1','Task text');
INSERT INTO task(name_task,task) VALUES('Task_2','Task text');
INSERT INTO task(name_task,task) VALUES('Task_3','Task text');